apiVersion: v1
kind: Service
metadata:
  name: whisker-lore-api
  namespace: work-apps
  labels:
    app: whisker-lore-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: whisker-lore-api
